name: Build upload artifacrtts

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0          

      - name: Build macOS natives
        run: ./build-macos.sh      

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: natives-macos
          path: |
            ffmpeg
            ffprobe

  natives-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0          

      - name: Build Linux natives
        run: ./build-linux.sh     

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: natives-linux
          path: |
            ffmpeg
            ffprobe

  natives-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: msys2/setup-msys2@v2

      - shell: msys2 {0}
        run: ./build-windows.sh          

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: natives-windows
          path: |
            ffmpeg.exe
            ffprobe.exe